version: '3.3'

services:
  app:
    build: ./
    image: spring-boot-accessingdatamysql
    restart: always
    ports:
      - "8080:8080"
    
  db:
    image: mysql:5.7
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: helloworld
      MYSQL_USER: helloworld
      MYSQL_PASSWORD: helloworld
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=helloworld
volumes:
    data_db: