version: '3.3'

services:
  app:
    build: ./
    image: spring-boot-accessingdatamysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/helloworld
      SPRING_DATASOURCE_USERNAME: helloworld
      SPRING_DATASOURCE_PASSWORD: helloworld
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: mysql:8
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: helloworld
      MYSQL_USER: helloworld
      MYSQL_PASSWORD: helloworld
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=helloworld
    depends_on:
      db:
        condition: service_healthy
volumes:
    data_db: